ADD_SUBDIRECTORY(protocol)
ADD_SUBDIRECTORY(common)
ADD_SUBDIRECTORY(consent)
ADD_SUBDIRECTORY(consentd)

IF(CONSENT_BUILD_TOOLS)
  ADD_SUBDIRECTORY(tools)
  ADD_SUBDIRECTORY(examples)
ENDIF()
IF(CONSENT_BUILD_POC)
  ADD_SUBDIRECTORY(mocks)
  ADD_SUBDIRECTORY(poc-tools)
ENDIF()
IF(BUILD_TESTING)
  ADD_SUBDIRECTORY(tests)
ENDIF()
