# Isolated development fixtures; production targets keep their own definitions.
IF(CONSENT_BUILD_SMOKE_TOOLS AND NOT CONSENT_BUILD_SMOKE)
  MESSAGE(FATAL_ERROR "CONSENT_BUILD_SMOKE_TOOLS requires CONSENT_BUILD_SMOKE")
ENDIF()
IF(NOT CONSENT_BUILD_SMOKE)
  RETURN()
ENDIF()
SET(SMOKE_ROOT "/tmp/consent-smoke")
SET(SMOKE_RUNTIME "/opt/var/lib/consent-smoke-runtime")
SET(SMOKE_STATE "/opt/var/lib/consent-smoke-state")
SET(SMOKE_AUTHORITY "/opt/var/lib/consent-smoke-authority")
SET(SMOKE_DEST "${CMAKE_INSTALL_LIBEXECDIR}/consent/smoke")
GET_TARGET_PROPERTY(SMOKE_CLIENT_SOURCES consent SOURCES)
ADD_LIBRARY(consent-smoke SHARED ${SMOKE_CLIENT_SOURCES})
TARGET_INCLUDE_DIRECTORIES(consent-smoke PUBLIC
  "${PROJECT_SOURCE_DIR}/src/consent/inc"
  PRIVATE "${PROJECT_SOURCE_DIR}/src/consent" "${PROJECT_SOURCE_DIR}/src")
TARGET_LINK_LIBRARIES(consent-smoke PUBLIC PkgConfig::CAPI_BASE_COMMON
  PRIVATE consent-common PkgConfig::GLIB Threads::Threads)
TARGET_COMPILE_DEFINITIONS(consent-smoke PRIVATE
  CONSENT_SOCKET_PATH="${SMOKE_RUNTIME}/consent.sock"
  CONSENT_AUTHORITY_DIR="${SMOKE_AUTHORITY}")
SET_TARGET_PROPERTIES(consent-smoke PROPERTIES VERSION "${PROJECT_VERSION}"
  SOVERSION 0)
SET_PROPERTY(TARGET consent-smoke APPEND_STRING PROPERTY LINK_FLAGS
  " -Wl,--version-script=${PROJECT_SOURCE_DIR}/packaging/consent.map")
SET_PROPERTY(TARGET consent-smoke APPEND PROPERTY LINK_DEPENDS
  "${PROJECT_SOURCE_DIR}/packaging/consent.map")
INSTALL(TARGETS consent-smoke LIBRARY DESTINATION "${SMOKE_DEST}")
GET_TARGET_PROPERTY(SMOKE_DAEMON_SOURCES consentd SOURCES)
ADD_EXECUTABLE(consentd-smoke ${SMOKE_DAEMON_SOURCES})
TARGET_INCLUDE_DIRECTORIES(consentd-smoke PRIVATE "${PROJECT_SOURCE_DIR}/src"
  "${PROJECT_SOURCE_DIR}/src/consent/inc")
TARGET_LINK_LIBRARIES(consentd-smoke PRIVATE consent-common consent-storage
  PkgConfig::GLIB PkgConfig::SQLITE PkgConfig::SYSTEMD Threads::Threads)
TARGET_COMPILE_DEFINITIONS(consentd-smoke PRIVATE CONSENT_TEST_BUILD
  CONSENT_LOG_TAG="CONSENTD" CONSENT_SOCKET_PATH="${SMOKE_RUNTIME}/consent.sock"
  CONSENT_STATE_DIR="${SMOKE_STATE}"
  CONSENT_AUTHORITY_DIR="${SMOKE_AUTHORITY}"
  CONSENT_SERVICE_UNIT="consentd-smoke.service"
  CONSENT_ROLE_CONFIG="${SMOKE_ROOT}/roles.conf"
  CONSENT_INSTALLATIONS="${SMOKE_AUTHORITY}/installations.conf")
INSTALL(TARGETS consentd-smoke RUNTIME DESTINATION "${SMOKE_DEST}")
FOREACH(TOOL storage-prepare installation-authority)
  STRING(REPLACE "-" "_" SOURCE "${TOOL}")
  ADD_EXECUTABLE(consent-smoke-${TOOL}
    "${PROJECT_SOURCE_DIR}/src/tools/${SOURCE}.cc")
  TARGET_INCLUDE_DIRECTORIES(consent-smoke-${TOOL} PRIVATE
    "${PROJECT_SOURCE_DIR}/src")
  TARGET_LINK_LIBRARIES(consent-smoke-${TOOL} PRIVATE consent-common
    PkgConfig::GLIB PkgConfig::SYSTEMD)
  TARGET_COMPILE_DEFINITIONS(consent-smoke-${TOOL} PRIVATE CONSENT_TEST_BUILD
    CONSENT_STATE_DIR="${SMOKE_STATE}"
    CONSENT_AUTHORITY_DIR="${SMOKE_AUTHORITY}"
    CONSENT_SERVICE_USER="${CONSENT_SERVICE_USER}"
    CONSENT_SERVICE_UNIT="consentd-smoke.service"
    CONSENT_INSTALLATIONS="${SMOKE_AUTHORITY}/installations.conf")
  INSTALL(TARGETS consent-smoke-${TOOL} RUNTIME DESTINATION "${SMOKE_DEST}")
ENDFOREACH()
ADD_SUBDIRECTORY(tests/smoke)
INSTALL(PROGRAMS scripts/emulator-smoke.py DESTINATION "${SMOKE_DEST}")
INSTALL(DIRECTORY tests/smoke/ DESTINATION
  "${CMAKE_INSTALL_DOCDIR}/tests/smoke" FILES_MATCHING PATTERN "*.c"
  PATTERN "*.h" PATTERN "cli.json")
