FILE(GLOB COMMON_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.cc")
IF(COMMON_SOURCES)
  ADD_LIBRARY(consent-common STATIC ${COMMON_SOURCES})
  TARGET_INCLUDE_DIRECTORIES(consent-common PUBLIC
    "${PROJECT_SOURCE_DIR}/src" "${CMAKE_CURRENT_SOURCE_DIR}"
    "${PROJECT_BINARY_DIR}/generated")
  TARGET_LINK_LIBRARIES(consent-common PUBLIC PkgConfig::GLIB PkgConfig::PARCEL Threads::Threads)
ELSE()
  ADD_LIBRARY(consent-common INTERFACE)
  TARGET_INCLUDE_DIRECTORIES(consent-common INTERFACE
    "${PROJECT_SOURCE_DIR}/src" "${CMAKE_CURRENT_SOURCE_DIR}"
    "${PROJECT_BINARY_DIR}/generated")
  TARGET_LINK_LIBRARIES(consent-common INTERFACE PkgConfig::GLIB PkgConfig::PARCEL Threads::Threads)
ENDIF()
ADD_DEPENDENCIES(consent-common consent-wire)
