#!/usr/bin/env python3
# Copyright (c) 2026 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Compile bounded JSON IDL into native Tizen Parcelable C++ records.

This deliberately small IDL accepts u32/i32/u64, bounded UTF-8 strings,
previously declared records, and bounded arrays of previously declared records.
Schema order defines wire order. There is no eval, import or source inclusion.
"""

import argparse
import json
import os
from pathlib import Path
import re
import sys
import tempfile


NUMERIC = {"u32": ("uint32_t", "U32", 0, 2**32 - 1),
           "i32": ("int32_t", "I32", -(2**31), 2**31 - 1),
           "u64": ("uint64_t", "U64", 0, 2**64 - 1)}
RESERVED = set("""alignas alignof and and_eq asm atomic_cancel atomic_commit
atomic_noexcept auto bitand bitor bool break case catch char char16_t char32_t
class compl concept const constexpr const_cast continue co_await co_return
co_yield decltype default delete do double dynamic_cast else enum explicit
export extern false float for friend goto if import inline int long module
mutable namespace new noexcept not not_eq nullptr operator or or_eq private
protected public register reinterpret_cast requires return short signed sizeof
static static_assert static_cast struct switch synchronized template this
thread_local throw true try typedef typeid typename union unsigned using virtual
void volatile wchar_t while xor xor_eq final override std tizen_base
Reader Writer Valid ValidString WriteToParcel ReadFromParcel
uint32_t int32_t uint64_t""".split())
COPYRIGHT = "Copyright (c) 2026 Samsung Electronics Co., Ltd. All Rights Reserved"
APACHE_NOTICE = """Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License."""
HEADER = """/*
 * Copyright (c) 2026 Samsung Electronics Co., Ltd. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by parcel_codegen.py. Edit the IDL source, not this file.
"""


def require(condition, message):
    if not condition:
        raise ValueError(message)


def identifier(value):
    return (isinstance(value, str) and
            re.fullmatch(r"[A-Za-z][A-Za-z0-9_]{0,63}", value) is not None and
            "__" not in value and value not in RESERVED)


def integer(value, minimum, maximum):
    return type(value) is int and minimum <= value <= maximum


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        require(key not in result, "duplicate JSON key: " + key)
        result[key] = value
    return result


def validate(schema):
    require(isinstance(schema, dict) and set(schema) == {"license", "namespace", "records"},
            "schema requires only license, namespace and records")
    require(schema["license"] == {"spdx": "Apache-2.0", "copyright": COPYRIGHT,
                                  "notice": APACHE_NOTICE},
            "schema requires the complete supported Apache-2.0 notice")
    namespace = schema["namespace"]
    require(isinstance(namespace, str) and
            all(identifier(part) for part in namespace.split("::")),
            "invalid namespace")
    records = schema["records"]
    require(isinstance(records, list) and 1 <= len(records) <= 64,
            "records must contain 1..64 entries")
    known = {}
    for record in records:
        require(isinstance(record, dict) and set(record) == {"name", "fields"},
                "record requires only name and fields")
        name = record["name"]
        require(identifier(name) and name[0].isupper() and name not in known,
                "invalid or duplicate record name")
        fields = record["fields"]
        require(isinstance(fields, list) and 1 <= len(fields) <= 64,
                "record fields must contain 1..64 entries")
        seen = set()
        minimum, maximum, fixed, heap, depth = 0, 0, 16, 0, 1
        for field in fields:
            require(isinstance(field, dict), "field must be an object")
            fname, kind = field.get("name"), field.get("type")
            require(identifier(fname) and fname[0].islower() and fname not in seen,
                    "invalid or duplicate field name")
            require(isinstance(kind, str), "field type must be a string")
            allowed = {"name", "type"}
            if kind in NUMERIC:
                allowed.add("default")
                info = NUMERIC[kind]
                require(integer(field.get("default", 0), info[2], info[3]),
                        "numeric default outside type bounds")
                width = 8 if kind == "u64" else 4
                minimum += width
                maximum += width
                fixed += 8
            elif kind == "string":
                allowed |= {"min_bytes", "max_bytes"}
                require(integer(field.get("max_bytes"), 1, 65536),
                        "string requires max_bytes in 1..65536")
                require(integer(field.get("min_bytes", 0), 0, field["max_bytes"]),
                        "invalid string min_bytes")
                minimum += 5 + field.get("min_bytes", 0)
                maximum += 5 + field["max_bytes"]
                fixed += 32
                heap += field["max_bytes"] + 1
            elif kind == "array":
                allowed |= {"element", "max_count"}
                require(isinstance(field.get("element"), str) and
                        field["element"] in known,
                        "array element must be an earlier record")
                require(integer(field.get("max_count"), 1, 4096),
                        "array requires max_count in 1..4096")
                child = known[field["element"]]
                minimum += 4
                maximum += 4 + field["max_count"] * child["maximum"]
                fixed += 24
                heap += field["max_count"] * (child["fixed"] + child["heap"])
                depth = max(depth, child["depth"] + 1)
            else:
                require(kind in known, "unknown, recursive or forward field type")
                child = known[kind]
                minimum += child["minimum"]
                maximum += child["maximum"]
                fixed += child["fixed"]
                heap += child["heap"]
                depth = max(depth, child["depth"] + 1)
            require(set(field) <= allowed, "unknown field constraint")
            seen.add(fname)
        require(depth <= 16 and minimum <= 65536 and fixed <= 65536 and
                maximum <= 16 * 1024 * 1024 and heap <= 16 * 1024 * 1024,
                "transitive record depth, wire size or layout exceeds limits")
        known[name] = {"minimum": minimum, "maximum": maximum, "fixed": fixed,
                       "heap": heap, "depth": depth}
    return known


def declaration(field):
    name, kind = field["name"], field["type"]
    if kind in NUMERIC:
        value = field.get("default", 0)
        suffix = "ULL" if kind == "u64" else "U" if kind == "u32" else ""
        return f"  ::std::{NUMERIC[kind][0]} {name} = {value}{suffix};"
    if kind == "string":
        return f"  std::string {name};"
    if kind == "array":
        return f"  std::vector<{field['element']}> {name};"
    return f"  {kind} {name};"


def emit_record(record, layout):
    name, fields = record["name"], record["fields"]
    out = [f"class {name} final : public tizen_base::Parcelable {{", " public:"]
    out.extend(declaration(field) for field in fields)
    out += ["", "  bool Valid() const {"]
    for field in fields:
        value, kind = "this->" + field["name"], field["type"]
        if kind == "string":
            conditions = f"!::consent::wire::ValidString({value}, {field['max_bytes']})"
            if field.get("min_bytes", 0):
                conditions += f" || {value}.size() < {field['min_bytes']}"
            out += [f"    if ({conditions})", "      return false;"]
        elif kind == "array":
            out += [f"    if ({value}.size() > {field['max_count']})",
                    "      return false;", f"    for (const auto& item : {value}) {{",
                    "      if (!item.Valid())", "        return false;", "    }"]
        elif kind not in NUMERIC:
            out += [f"    if (!{value}.Valid())", "      return false;"]
    out += ["    return true;", "  }", "",
            "  void WriteToParcel(tizen_base::Parcel* parcel) const override {",
            "    if (!parcel || !Valid())",
            '      throw std::invalid_argument("invalid IDL record");',
            "    [[maybe_unused]] ::consent::wire::Writer writer(parcel);"]
    for field in fields:
        value, kind = "this->" + field["name"], field["type"]
        call = None
        if kind in NUMERIC:
            call = f"writer.{NUMERIC[kind][1]}({value})"
        elif kind == "string":
            call = f"writer.String({value}, {field['max_bytes']})"
        elif kind == "array":
            call = f"writer.U32(static_cast<::std::uint32_t>({value}.size()))"
        if call:
            out += [f"    if (!{call})",
                    '      throw std::invalid_argument("parcel write failed");']
        if kind == "array":
            out += [f"    for (const auto& item : {value})", "      item.WriteToParcel(parcel);"]
        elif kind not in NUMERIC and kind != "string":
            out += [f"    {value}.WriteToParcel(parcel);"]
    out += ["  }", "", "  void ReadFromParcel(tizen_base::Parcel* parcel) override {",
            "    if (!parcel)", '      throw std::invalid_argument("null parcel");',
            "    [[maybe_unused]] ::consent::wire::Reader reader(parcel);", f"    {name} decoded;"]
    for field in fields:
        fname, kind = field["name"], field["type"]
        value = "decoded." + fname
        call = None
        if kind in NUMERIC:
            call = f"reader.{NUMERIC[kind][1]}(&{value})"
        elif kind == "string":
            call = f"reader.String(&{value}, {field['max_bytes']})"
        elif kind == "array":
            out += [f"    ::std::uint32_t count_{fname} = 0;"]
            call = f"reader.U32(&count_{fname}) || count_{fname} > {field['max_count']}"
        if call:
            out += [f"    if (!{call})" if kind != "array" else
                    f"    if (!reader.U32(&count_{fname}) || count_{fname} > {field['max_count']})",
                    '      throw std::invalid_argument("parcel read failed");']
        if kind == "array":
            minimum = layout[field["element"]]["minimum"]
            out += ["    if (parcel->GetReader() > parcel->GetDataSize() ||",
                    f"        count_{fname} > (parcel->GetDataSize() - parcel->GetReader()) / {minimum})",
                    '      throw std::invalid_argument("array exceeds remaining parcel");',
                    f"    {value}.resize(count_{fname});", f"    for (auto& item : {value})",
                    "      item.ReadFromParcel(parcel);"]
        elif kind not in NUMERIC and kind != "string":
            out += [f"    {value}.ReadFromParcel(parcel);"]
    out += ["    if (!decoded.Valid())", '      throw std::invalid_argument("invalid IDL record");',
            "    *this = std::move(decoded);", "  }", "};", ""]
    return out


def generate(schema):
    layout = validate(schema)
    namespace = schema["namespace"]
    guard = "CONSENT_GENERATED_" + namespace.replace("::", "_").upper() + "_HH_"
    out = [HEADER.rstrip(), f"#ifndef {guard}", f"#define {guard}", "",
           "#include <cstdint>", "#include <stdexcept>", "#include <string>",
           "#include <utility>", "#include <vector>", "#include <parcelable.hh>", "",
           '#include "common/parcel_codec.hh"', "", f"namespace {namespace} {{", ""]
    for record in schema["records"]:
        out.extend(emit_record(record, layout))
    out += [f"}}  // namespace {namespace}", "", f"#endif  // {guard}", ""]
    return "\n".join(out)


def load(path):
    raw = Path(path).read_bytes()
    require(len(raw) <= 65536, "IDL exceeds 65536 bytes")
    return json.loads(raw.decode("utf-8"), object_pairs_hook=unique_object)


def write_output(path, content):
    output = Path(path)
    if output.exists() and output.read_text(encoding="utf-8") == content:
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    name = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n",
                                         dir=str(output.parent), delete=False) as stream:
            name = stream.name
            stream.write(content)
        os.chmod(name, 0o644)
        os.replace(name, output)
        name = None
    finally:
        if name is not None:
            os.unlink(name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("schema")
    parser.add_argument("output", nargs="?")
    parser.add_argument("--check", action="store_true", help="validate without writing")
    args = parser.parse_args()
    if not args.check and not args.output:
        parser.error("output is required unless --check is used")
    try:
        content = generate(load(args.schema))
        if not args.check:
            write_output(args.output, content)
    except (ValueError, OSError, UnicodeError, RecursionError) as error:
        print("parcel_codegen: " + str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
